name: Deploy
on:
  schedule:
    - cron: '23 4 * * *' # Once, nightly
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.DEPLOY_HOOK }}
